spring:
  application:
    name: backend

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: APP_USER
    password: AppUser123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none           # let Liquibase manage schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    open-in-view: false
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080
